name: utp_in_me
description: An Universiti Teknologi PETRONAS application

publish_to: 'none'

version: 23.1.26070517

environment:
  sdk: '>=2.18.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  gridview_menu: ^1.0.6
  nfc_manager: ^3.2.0
  webview_flutter: ^4.0.2
  flutter_launcher_icons: "^0.9.0"
  google_maps_flutter: ^2.2.3
  qr_flutter: ^4.0.0
  google_fonts: ^3.0.1
  material_color_utilities: ^0.2.0
  desktop_window: ^0.4.0
  dynamic_color: ^1.5.4
  url_launcher: ^6.1.8
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
  - assets/profile_pic.png
  - assets/chan.jpg
  - assets/UTP-logo.png
  - assets/ch.jpg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
