name: utp_in_me
description: UTP Gimmick Official Application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 23.1.24010012

environment:
  sdk: '>=2.18.5 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  gridview_menu: ^1.0.6
  webview_flutter: ^4.0.1
  flutter_launcher_icons: "^0.9.0"
  google_maps_flutter: ^2.2.3
  qr_flutter: ^4.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
  - assets/profile_pic.png
  - assets/chan.jpg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
