name: utp_in_me
description: An Universiti Teknologi PETRONAS application

publish_to: 'none'

version: 23.2.672021413358

environment:
  sdk: '>=2.18.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  gridview_menu: ^1.0.6
  flutter_polyline_points: ^1.0.0
  webview_flutter: ^4.0.2
  flutter_launcher_icons: ^0.13.1
  flutter_map:
        git:
            url: https://github.com/fleaflet/flutter_map.git
  #google_maps_flutter: ^2.2.3
  qr_flutter: ^4.1.0
  google_fonts: ^4.0.4
  material_color_utilities: ^0.2.0
  #location: ^4.4.0
  flutter_svg: ^2.0.0+1
  #permission_handler: ^10.2.0
  dynamic_color: ^1.5.4
  quick_actions: ^1.0.1
  #adaptive_navigation: ^0.0.9
  latlong2: ^0.8.1
  qr_code_scanner: ^1.0.1
  xml2json: ^6.0.0
  http: ^0.13.4
  url_launcher: ^6.0.18
  cached_network_image: ^3.2.0
  #flutter_html: ^2.2.1
  webfeed_revised: ^0.7.0

  
 
 
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
  - assets/profile_pic.png
  - assets/chan.jpg
  - assets/UTP-logo.png
  - assets/ch.jpg

  fonts:
      - family: GoogleSans
        fonts:
          - asset: assets/fonts/google_sans_regular.ttf
          - asset: assets/fonts/google_sans_italic.ttf
            style: italic
 
